### ISSUE TITLE
301 Protocol "blob" is unknown

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubuntu-download-manager#1]
Download of content (i.e. images from web.telegram.org, «exported» images from photopea.com, etc) starts to download but content is not handled / accessible.

How to reproduce:
1) Go to photopea.com
2) open an image or create a blank project
3) File > export as > png and save
4) Choose Download
Result:
xxx-xxxx-xxxxx
blob:https://www.photopea.com/xxx-xxxxx-xxxxx
NetworkError: 301 - Protocol "blob" is unkonw

Expected result:
Let user to decide what to do with blob info

**Comment by dpniel** [comment]
THis is a long standing [bug](https://bugs.launchpad.net/ubuntu/+source/webbrowser-app/+bug/1490749) (see chris's comment on how it also affects `blob`) with no real idea on how to address it. The chrome browser (not webview) in android has the same limitations i think.

**Comment by cibersheep** [comment]
I see. So, it means the idea of having such «filesystem:», «blob:» etc, is to know what type of «link» it is what are we handeling, right?

Would be a working (even if dirty) workaround to parse the link without the «XX:»?
@bhdouglass?

**Comment by bhdouglass** [comment]
So I just tried this on my desktop:
1) Create a new project and exported it from photopea.com
2) Copied the `blob:` url and attempted to download it via `wget` (without the `blob:` part)
3) Failed to download with a 404 error

Apparently these blob urls aren't actual urls on the server, they are just special browser only things. So it sounds like the download manager couldn't do anything here, it would have to be the browser itself doing the "downloading". So it looks like a dirty hack won't work here.

**Comment by cibersheep** [comment]
Oooook. So, I'm closing this and open the issue in oxide.
Thanks and sorry

Just for knowledge: https://superuser.com/questions/948738/what-is-the-blobhttp-prefix-and-where-can-i-learn-more-about-this
