### ISSUE TITLE
Zip file downloaded with SingleDownload, is deleted if metadata extract is set to true

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubuntu-download-manager#26]
According to the docs settings extract will try to extract the file after download

```
    SingleDownload {
        id: download

        metadata: Metadata {
            extract: true 
        }
    }
```

when zip file is dowload I get the url but the zip file is deleted. And no extracted files

Download manager doesn't through any error? line 70? http://paste.ubuntu.com/p/FWTJNrz6VX/

**Comment by UniversalSuperBox** [comment]
Thanks for your report. This repository is moving to GitLab, and I have reopened this issue there as https://gitlab.com/ubports/core/lomiri-download-manager/-/issues/5
