### ISSUE TITLE
If no network, Single Download cannot be cancelled

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubuntu-download-manager#30]
Having SingleDownload{}
- Disconnect internet connection
- trigger download
- after having no network error i.e. `NetworkError: 3 - Host [].org not found`, cancel() the download

downloading = true (should be false)
downloadInProgress = true (should be true?)

**Comment by UniversalSuperBox** [comment]
Thanks for your report. This repository is moving to GitLab, and I have reopened this issue there as https://gitlab.com/ubports/core/lomiri-download-manager/-/issues/6
