### ISSUE TITLE
Downloads directory is not emptied

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubuntu-download-manager#31]
Downloading file with a SingleDownload{} element will add downloaded elements in `~/.local/share/ubuntu-download-manager/[App Name]/Downloads/` without a way of empty the directory

**Comment by UniversalSuperBox** [comment]
Thanks for your report. This repository is moving to GitLab, and I have reopened this issue there as https://gitlab.com/ubports/core/lomiri-download-manager/-/issues/7
