### ISSUE TITLE
Apps using download manager crashes

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubuntu-download-manager#32]
- Open Podbird
- Download an episode

-> The app crashes until rebooting the device

Tested on Arale and Vegeta Dev channel 2021-03-23

Logs: line 85? http://paste.ubuntu.com/p/QFVb9Dj7zj/

**Comment by dobey** [comment]
This is fixed by https://gitlab.com/ubports/core/click-apparmor/-/merge_requests/3
