### ISSUE TITLE
downoad manager creates garbage logfiles

### ISSUE THREAD

**Issue by Flohack74** [ubports/ubuntu-download-manager#33]
Something is wrong with the logfile creation in download manager:
![grafik](https://user-images.githubusercontent.com/16186470/118354676-7fca6c80-b56c-11eb-8f5d-9a2e72c8cf72.png)
The files cannot be extracted from a tgz archive anymore since they also have invalid datetimes

**Comment by UniversalSuperBox** [comment]
Thanks for your report. This repository is moving to GitLab, and I have reopened this issue there as https://gitlab.com/ubports/core/lomiri-download-manager/-/issues/8
