### ISSUE TITLE
Unknown option 'qt'

### ISSUE THREAD

**Issue by vanyasem** [ubports/ubuntu-download-manager#6]
I get this error when building on Arch GNU/Linux (amd64)
```
Unknown option 'qt'.
make[2]: *** [docs/qml/CMakeFiles/qmldoc.dir/build.make:58: docs/qml/CMakeFiles/qmldoc] Error 1
make[1]: *** [CMakeFiles/Makefile2:4153: docs/qml/CMakeFiles/qmldoc.dir/all] Error 2
```

The troubling options resides in `docs/qml/CMakeLists.txt` on line 6.

The issue is related to `qdoc`: `/usr/bin/qdoc -qt=qt5`

**Comment by UniversalSuperBox** [comment]
Thanks for your report. This repository is moving to GitLab, and I have reopened this issue there as https://gitlab.com/ubports/core/lomiri-download-manager/-/issues/4
