### ISSUE TITLE
SingleDownload property: downloadInProgress is always false

### ISSUE THREAD

**Issue by cibersheep** [ubports/ubuntu-download-manager#8]
When downloading a file with
```
import Ubuntu.DownloadManager 1.2

SingleDownload {
    id: single
}
```
property `single.downloadInProgress` is always false

**Comment by cibersheep** [comment]
After [fixing](https://github.com/ubports/ubuntu-download-manager/issues/10) the property onChanged this works (tested on cooler)

![imatge](https://user-images.githubusercontent.com/6640041/50579715-f527bd80-0e47-11e9-9246-3d7815e1521d.png)

```
qml: DEBUG: downloadInProgress is true
qml: Download path: /home/[...]/Downloads title Zork-The_Forces_of_Krill-(1.0).ibs
qml: DEBUG: downloadInProgress is false
```

**Comment by NeoTheThird** [comment]
Seems to work fine, good job!
